export const MOBILE_VALID_FROM = '2026-01-30'

export const MOBILE_FOREIGN_RATES: Record<string, { rate_12: number; currency: string }> = {
    AT: { rate_12: 63,   currency: 'EUR' },
    BE: { rate_12: 63,   currency: 'EUR' },
    BG: { rate_12: 43,   currency: 'EUR' },
    BY: { rate_12: 55,   currency: 'EUR' },
    CY: { rate_12: 57,   currency: 'EUR' },
    CZ: { rate_12: 1200, currency: 'CZK' },
    DE: { rate_12: 63,   currency: 'EUR' },
    DK: { rate_12: 456,  currency: 'DKK' },
    EE: { rate_12: 50,   currency: 'EUR' },
    ES: { rate_12: 60,   currency: 'EUR' },
    FI: { rate_12: 60,   currency: 'EUR' },
    FR: { rate_12: 63,   currency: 'EUR' },
    GR: { rate_12: 59,   currency: 'EUR' },
    HR: { rate_12: 56,   currency: 'EUR' },
    HU: { rate_12: 55,   currency: 'EUR' },
    IE: { rate_12: 64,   currency: 'EUR' },
    IT: { rate_12: 63,   currency: 'EUR' },
    LT: { rate_12: 56,   currency: 'EUR' },
    LU: { rate_12: 60,   currency: 'EUR' },
    LV: { rate_12: 56,   currency: 'EUR' },
    MT: { rate_12: 54,   currency: 'EUR' },
    NL: { rate_12: 63,   currency: 'EUR' },
    PL: { rate_12: 52,   currency: 'EUR' },
    PT: { rate_12: 60,   currency: 'EUR' },
    RO: { rate_12: 60,   currency: 'EUR' },
    RS: { rate_12: 60,   currency: 'EUR' },
    RU: { rate_12: 55,   currency: 'EUR' },
    SE: { rate_12: 637,  currency: 'SEK' },
    SI: { rate_12: 53,   currency: 'EUR' },
    TR: { rate_12: 62,   currency: 'EUR' },
    UA: { rate_12: 52,   currency: 'EUR' },
}
