import type { StravneRates, StravneRatesEntry } from '../types'

export const TRANSPORT_OPTIONS = [
    { value: 'car',         label: 'Vlastné auto (AUV)', short: 'AUV' },
    { value: 'company_car', label: 'Firemné auto (AUS)',  short: 'AUS' },
    { value: 'train',       label: 'Vlak',                short: 'R/O' },
    { value: 'bus',         label: 'Autobus',             short: 'A'   },
    { value: 'plane',       label: 'Lietadlo',            short: 'L'   },
    { value: 'other',       label: 'Iné',                 short: '—'   },
]

export const COUNTRY_OPTIONS = [
    { code: 'SK', label: 'Slovensko',        currency: 'EUR', borderPrefix: ''     },
    { code: 'CZ', label: 'Česká republika',  currency: 'CZK', borderPrefix: 'CZ'  },
    { code: 'HU', label: 'Maďarsko',         currency: 'HUF', borderPrefix: 'HU'  },
    { code: 'AT', label: 'Rakúsko',          currency: 'EUR', borderPrefix: 'AT'  },
    { code: 'PL', label: 'Poľsko',           currency: 'PLN', borderPrefix: 'PL'  },
    { code: 'DE', label: 'Nemecko',          currency: 'EUR', borderPrefix: 'DE'  },
    { code: 'UA', label: 'Ukrajina',         currency: 'UAH', borderPrefix: 'UA'  },
    { code: 'OTHER', label: 'Iná krajina',   currency: 'EUR', borderPrefix: 'XX'  },
]


export const STATUS_OPTIONS = [
    { value: 'navrh',    label: 'Návrh' },
    { value: 'approved', label: 'Schválený' },
    { value: 'settled',  label: 'Vyúčtovaný' },
]

export const STATUS_MAP: Record<string, { label: string; color: 'default' | 'info' | 'success' | 'warning' }> = {
    draft:    { label: 'Koncept',     color: 'default' },
    navrh:    { label: 'Návrh',       color: 'warning' },
    approved: { label: 'Schválený',   color: 'info' },
    settled:  { label: 'Vyúčtovaný', color: 'success' },
}

export const EXPENSE_TYPES = [
    { value: 'cestovne', label: 'Cestovné' },
    { value: 'noclazne', label: 'Nocľažné' },
    { value: 'nutne',    label: 'Nutné náhrady' },
    { value: 'vreckove', label: 'Vreckové' },
    { value: 'ine',      label: 'Iné náhrady' },
]

export const PURPOSE_SUGGESTIONS = [
    'Obchodné rokovanie',
    'Obchodné stretnutie',
    'Pracovná porada',
    'Školenie',
    'Konferencia',
    'Seminár',
    'Servisný zásah',
    'Technická obhliadka',
    'Inštalácia',
    'Montáž',
    'Zákaznícka podpora',
    'Odborná návšteva',
    'Prezentácia',
    'Podpis zmluvy',
    'Audit',
    'Výstavka / veľtrh',
    'Reklamačné konanie',
    'Konzultácia',
    'Projektová porada',
    'Výberové konanie',
    'Obhliadka',
]

export const CITY_SUGGESTIONS: Record<string, string[]> = {
    SK: [
        // Krajské mestá
        'Bratislava', 'Košice', 'Prešov', 'Žilina', 'Banská Bystrica', 'Nitra', 'Trnava', 'Trenčín',
        // Okresné mestá a väčšie sídla
        'Martin', 'Poprad', 'Zvolen', 'Komárno', 'Liptovský Mikuláš', 'Ružomberok', 'Spišská Nová Ves',
        'Michalovce', 'Bardejov', 'Humenné', 'Piešťany', 'Topoľčany', 'Prievidza', 'Partizánske',
        'Považská Bystrica', 'Nové Zámky', 'Levice', 'Hlohovec', 'Skalica', 'Senica', 'Dunajská Streda',
        'Galanta', 'Šaľa', 'Zlaté Moravce', 'Sabinov', 'Stará Ľubovňa', 'Kežmarok', 'Levoča',
        'Vranov nad Topľou', 'Stropkov', 'Snina', 'Sobrance', 'Rimavská Sobota', 'Rožňava', 'Revúca',
        'Brezno', 'Detva', 'Veľký Krtíš', 'Poltár', 'Dolný Kubín', 'Čadca', 'Kysucké Nové Mesto',
        'Bytča', 'Myjava', 'Nové Mesto nad Váhom', 'Ilava', 'Púchov', 'Handlová', 'Bojnice',
        'Turčianske Teplice', 'Vrútky', 'Rajec', 'Námestovo', 'Tvrdošín', 'Oravský Podzámok',
        'Liptovský Hrádok', 'Ružomberok', 'Svit', 'Spišská Belá', 'Gelnica', 'Moldava nad Bodvou',
        'Trebišov', 'Strážske', 'Vranov nad Topľou', 'Skalité', 'Krásno nad Kysucou',
        'Vel\'ké Kapušany', 'Senec', 'Pezinok', 'Svätý Jur', 'Malacky', 'Stupava', 'Záhorská Bystrica',
        'Modra', 'Smolenice', 'Vrbové', 'Leopoldov', 'Šintava', 'Sereď', 'Kolárovo', 'Štúrovo',
        'Hurbanovo', 'Šurany', 'Vráble', 'Želiezovce', 'Šahy', 'Pukanec', 'Tlmače', 'Žiar nad Hronom',
        'Nová Baňa', 'Žarnovica', 'Banská Štiavnica', 'Krupina', 'Fiľakovo', 'Lučenec', 'Tornaľa',
        'Tisovec', 'Kalinovo', 'Kokava nad Rimavicou', 'Hnúšťa', 'Dobšiná', 'Spišské Podhradie',
        'Krompachy', 'Košická Nová Ves', 'Senica', 'Holíč', 'Gbely', 'Brezová pod Bradlom',
        'Nové Zámky', 'Hurbanovo', 'Kalná nad Hronom', 'Vieska', 'Tesárske Mlyňany',
        'Bytča', 'Rajec', 'Stará Turá', 'Bošáca', 'Horné Srnie', 'Zliechov',
        'Žilina', 'Bytčica', 'Hričovské Podhradie', 'Rosina', 'Strečno', 'Varín',
        'Terchová', 'Belá', 'Kraľovany', 'Párnica', 'Istebné', 'Zubrohlava',
        'Trstená', 'Suchá Hora', 'Oravice', 'Zuberec', 'Liesek',
    ],
    CZ: [
        'Praha', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc', 'České Budějovice', 'Pardubice',
        'Hradec Králové', 'Zlín', 'Jihlava', 'Opava', 'Frýdek-Místek', 'Karviná', 'Uherské Hradiště',
        'Most', 'Teplice', 'Děčín', 'Kladno', 'Chomutov', 'Ústí nad Labem', 'Prostějov', 'Přerov',
        'Havířov', 'Třinec', 'Znojmo', 'Blansko', 'Hodonín', 'Kroměříž', 'Vsetín', 'Valašské Meziříčí',
        'Nový Jičín', 'Šumperk', 'Jeseník', 'Zábřeh', 'Žďár nad Sázavou', 'Třebíč', 'Pelhřimov',
        'Tábor', 'Písek', 'Strakonice', 'Klatovy', 'Cheb', 'Sokolov', 'Karlovy Vary', 'Jablonec nad Nisou',
        'Mladá Boleslav', 'Kolín', 'Kutná Hora', 'Příbram', 'Beroun', 'Rakovník', 'Mělník', 'Benešov',
        'Trutnov', 'Náchod', 'Jičín', 'Česká Lípa', 'Rumburk', 'Varnsdorf', 'Litoměřice', 'Louny',
        'Rokycany', 'Domažlice', 'Sušice', 'Prachatice', 'Český Krumlov', 'Jindřichův Hradec',
        'Třeboň', 'Dačice', 'Znojmo', 'Moravské Budějovice', 'Vyškov', 'Bučovice', 'Slavkov u Brna',
        'Rousínov', 'Kuřim', 'Tišnov', 'Boskovice', 'Velké Meziříčí', 'Moravský Krumlov',
        'Uherský Brod', 'Bojkovice', 'Luhačovice', 'Slavičín', 'Rožnov pod Radhoštěm',
        'Frenštát pod Radhoštěm', 'Kopřivnice', 'Příbor', 'Bílovec', 'Krnov', 'Bruntál',
        'Rýmařov', 'Šternberk', 'Litovel', 'Uničov', 'Mohelnice', 'Zábřeh', 'Lanškroun',
        'Česká Třebová', 'Svitavy', 'Litomyšl', 'Polička', 'Chrudim', 'Hlinsko', 'Čáslav',
        'Nymburk', 'Poděbrady', 'Lysá nad Labem', 'Brandýs nad Labem', 'Neratovice',
        'Říčany', 'Černošice', 'Dobříš', 'Sedlčany', 'Votice', 'Vlašim', 'Ledeč nad Sázavou',
        'Havlíčkův Brod', 'Chotěboř', 'Přibyslav', 'Humpolec', 'Pacov', 'Kamenice nad Lipou',
    ],
    HU: [
        'Budapešť', 'Debrecen', 'Miskolc', 'Győr', 'Pécs', 'Nyíregyháza', 'Kecskemét', 'Székesfehérvár',
        'Šoproň', 'Komárno (Komárom)', 'Eger', 'Tatabánya', 'Kaposvár', 'Szolnok', 'Érd',
        'Veszprém', 'Zalaegerszeg', 'Szombathely', 'Dunaújváros', 'Budaörs', 'Mosonmagyaróvár',
        'Gödöllő', 'Esztergom', 'Pápa', 'Ajka', 'Balassagyarmat', 'Salgótarján', 'Gyöngyös',
        'Hatvan', 'Cegléd', 'Jászberény', 'Szentes', 'Hódmezővásárhely', 'Orosháza', 'Békéscsaba',
        'Gyula', 'Makó', 'Szarvas', 'Törökszentmiklós', 'Tiszafüred', 'Kisvárda', 'Mátészalka',
        'Vác', 'Dunakeszi', 'Szentendre', 'Visegrád', 'Esztergom', 'Dorog', 'Oroszlány', 'Kisbér',
        'Győr', 'Csorna', 'Kapuvár', 'Fertőd', 'Fertőszentmiklós', 'Celldömölk', 'Sárvár',
        'Körmend', 'Szentgotthárd', 'Kőszeg', 'Bük', 'Vasvár', 'Nagykanizsa', 'Marcali',
        'Fonyód', 'Siófok', 'Balatonföldvár', 'Balatonfüred', 'Badacsony', 'Keszthely', 'Hévíz',
        'Tapolca', 'Sümeg', 'Devecser', 'Zirc', 'Várpalota', 'Polgárdi', 'Enying',
        'Dunaföldvár', 'Paks', 'Szekszárd', 'Bátaszék', 'Bonyhád', 'Dombóvár', 'Tamási',
        'Mohács', 'Siklós', 'Harkány', 'Szigetvár', 'Sellye', 'Barcs', 'Csurgó',
        'Marcali', 'Lengyeltóti', 'Balatonlelle', 'Fonyód',
        'Miskolc', 'Kazincbarcika', 'Ózd', 'Putnok', 'Edelény', 'Encs', 'Abaújszántó',
        'Szerencs', 'Tokaj', 'Sátoraljaújhely', 'Sárospatak', 'Kisvárda', 'Záhony',
        'Fehérgyarmat', 'Vásárosnamény', 'Nyírbátor', 'Hajdúböszörmény', 'Hajdúszoboszló',
        'Berettyóújfalu', 'Püspökladány', 'Karcag', 'Túrkeve', 'Mezőtúr',
    ],
    AT: [
        'Viedeň', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt', 'Bregenz', 'Eisenstadt',
        'Wiener Neustadt', 'Baden bei Wien', 'Wels', 'Steyr', 'Feldkirch', 'Dornbirn', 'Wolfsberg',
        'Leoben', 'Kapfenberg', 'Mödling', 'Klosterneuburg', 'Stockerau', 'Krems an der Donau',
        'St. Pölten', 'Amstetten', 'Waidhofen an der Ybbs', 'Schwechat', 'Perchtoldsdorf',
        'Villach', 'Spittal an der Drau', 'Völkermarkt', 'Lienz', 'Bruck an der Mur',
        'Knittelfeld', 'Judenburg', 'Murau', 'Voitsberg', 'Deutschlandsberg', 'Leibnitz',
        'Feldbach', 'Weiz', 'Hartberg', 'Fürstenfeld', 'Oberwart', 'Güssing', 'Jennersdorf',
        'Mattersburg', 'Neusiedl am See', 'Rust', 'Mörbisch', 'Sauerbrunn',
        'Mistelbach', 'Gänserndorf', 'Korneuburg', 'Tulln', 'Hollabrunn', 'Horn', 'Zwettl',
        'Waidhofen an der Thaya', 'Gmünd', 'Krems', 'Melk', 'Scheibbs', 'Lilienfeld',
        'Baden', 'Traiskirchen', 'Mödling', 'Bruck an der Leitha', 'Hainburg', 'Kittsee',
        'Perg', 'Freistadt', 'Rohrbach', 'Urfahr', 'Vöcklabruck', 'Gmunden', 'Bad Ischl',
        'Hallstatt', 'Schladming', 'Zell am See', 'Saalfelden', 'Hallein', 'Bischofshofen',
        'Wörgl', 'Kufstein', 'Schwaz', 'Hall in Tirol', 'Telfs', 'Imst', 'Landeck', 'Reutte',
        'Lienz', 'Hermagor', 'Sankt Veit an der Glan', 'Feldkirchen', 'Bleiburg', 'Wolfsberg',
        'Bludenz', 'Dornbirn', 'Hohenems', 'Lustenau', 'Hard', 'Rankweil',
    ],
    PL: [
        'Varšava', 'Kraków', 'Wrocław', 'Poznań', 'Gdansk', 'Katowice', 'Bydgoszcz', 'Lublin',
        'Rzeszów', 'Szczecin', 'Białystok', 'Sosnowiec', 'Bytom', 'Zabrze', 'Gliwice', 'Gdynia',
        'Częstochowa', 'Radom', 'Łódź', 'Kielce', 'Toruń', 'Olsztyn', 'Tychy', 'Rybnik',
        'Ruda Śląska', 'Opole', 'Elbląg', 'Gorzów Wielkopolski', 'Dąbrowa Górnicza', 'Zielona Góra',
        'Płock', 'Nowy Sącz', 'Tarnów', 'Bielsko-Biała', 'Krosno', 'Przemyśl', 'Sanok', 'Stalowa Wola',
        'Mielec', 'Nowy Targ', 'Zakopane', 'Cieszyn', 'Żywiec', 'Oświęcim', 'Jaworzno',
        'Chorzów', 'Siemianowice Śląskie', 'Mysłowice', 'Będzin', 'Czeladź', 'Czechowice-Dziedzice',
        'Pszczyna', 'Wodzisław Śląski', 'Żory', 'Jastrzębie-Zdrój', 'Knurów', 'Mikołów',
        'Tarnowskie Góry', 'Piekary Śląskie', 'Świętochłowice', 'Łaziska Górne', 'Lędziny',
        'Nowa Ruda', 'Kłodzko', 'Świdnica', 'Wałbrzych', 'Jelenia Góra', 'Legnica', 'Lubin',
        'Głogów', 'Polkowice', 'Bolesławiec', 'Zgorzelec', 'Bogatynia', 'Görlitz',
        'Leszno', 'Kalisz', 'Ostrów Wielkopolski', 'Gniezno', 'Konin', 'Turek', 'Kłodawa',
        'Piła', 'Chodzież', 'Wągrowiec', 'Szamotuły', 'Środa Wielkopolska', 'Jarocin',
        'Włocławek', 'Grudziądz', 'Inowrocław', 'Świecie', 'Chełmno', 'Brodnica', 'Rypin',
        'Lipno', 'Sierpc', 'Żuromin', 'Mława', 'Ciechanów', 'Przasnysz', 'Maków Mazowiecki',
        'Wyszków', 'Ostrów Mazowiecka', 'Łomża', 'Grajewo', 'Suwałki', 'Augustów', 'Sejny',
        'Sokółka', 'Mońki', 'Zambrów', 'Kolno', 'Wysokie Mazowieckie', 'Bielsk Podlaski',
        'Hajnówka', 'Siemiatycze', 'Bielsk Podlaski', 'Sokołów Podlaski', 'Siedlce', 'Biała Podlaska',
        'Chełm', 'Zamość', 'Hrubieszów', 'Tomaszów Lubelski', 'Kraśnik', 'Świdnik', 'Puławy',
        'Dęblin', 'Ryki', 'Garwolin', 'Kozienice', 'Grójec', 'Żyrardów', 'Skierniewice',
        'Łowicz', 'Kutno', 'Koło', 'Łęczyca', 'Zgierz', 'Pabianice', 'Zduńska Wola', 'Sieradz',
        'Wieluń', 'Pajęczno', 'Bełchatów', 'Piotrków Trybunalski', 'Tomaszów Mazowiecki',
        'Opoczno', 'Końskie', 'Skarżysko-Kamienna', 'Starachowice', 'Ostrowiec Świętokrzyski',
        'Staszów', 'Busko-Zdrój', 'Jędrzejów', 'Włoszczowa', 'Kazimierza Wielka',
        'Nowy Dwór Mazowiecki', 'Legionowo', 'Wołomin', 'Otwock', 'Piaseczno', 'Pruszków',
        'Piastów', 'Józefów', 'Zielonka', 'Kobyłka', 'Marki', 'Ząbki',
    ],
    DE: [
        'Berlín', 'Mníchov', 'Hamburg', 'Frankfurt nad Mohanom', 'Kolín nad Rýnom', 'Stuttgart',
        'Düsseldorf', 'Dortmund', 'Norimberg', 'Drážďany', 'Lipsko', 'Bremen', 'Hannover', 'Duisburg',
        'Bochum', 'Wuppertal', 'Bielefeld', 'Bonn', 'Mannheim', 'Karlsruhe', 'Augsburg', 'Wiesbaden',
        'Mönchengladbach', 'Gelsenkirchen', 'Aachen', 'Braunschweig', 'Kiel', 'Chemnitz', 'Halle',
        'Magdeburg', 'Freiburg im Breisgau', 'Krefeld', 'Erfurt', 'Mainz', 'Lübeck', 'Oberhausen',
        'Rostock', 'Kassel', 'Hagen', 'Hamm', 'Saarbrücken', 'Mülheim an der Ruhr', 'Potsdam',
        'Osnabrück', 'Heidelberg', 'Darmstadt', 'Würzburg', 'Regensburg', 'Ingolstadt', 'Ulm',
        'Heilbronn', 'Pforzheim', 'Offenburg', 'Konstanz', 'Passau', 'Bamberg', 'Bayreuth',
        'Recklinghausen', 'Münster', 'Solingen', 'Leverkusen', 'Herne', 'Neuss', 'Paderborn',
        'Remscheid', 'Fürth', 'Wolfsburg', 'Göttingen', 'Bottrop', 'Reutlingen', 'Koblenz',
        'Bremerhaven', 'Moers', 'Siegen', 'Hildesheim', 'Schwerin', 'Cottbus', 'Witten',
        'Zwickau', 'Jena', 'Gera', 'Dessau', 'Halle-Neustadt', 'Suhl', 'Eisenach', 'Weimar',
        'Erfurt', 'Gotha', 'Nordhausen', 'Mühlhausen', 'Arnstadt', 'Ilmenau', 'Schmalkalden',
        'Plauen', 'Zwickau', 'Aue', 'Freiberg', 'Meißen', 'Pirna', 'Bautzen', 'Görlitz',
        'Hoyerswerda', 'Riesa', 'Döbeln', 'Grimma', 'Torgau', 'Wurzen', 'Oschatz', 'Eilenburg',
        'Delitzsch', 'Bitterfeld', 'Merseburg', 'Weißenfels', 'Zeitz', 'Naumburg', 'Apolda',
        'Gießen', 'Marburg', 'Fulda', 'Hanau', 'Offenbach am Main', 'Rüsselsheim', 'Darmstadt',
        'Bensheim', 'Weinheim', 'Viernheim', 'Lampertheim', 'Lorsch', 'Heppenheim', 'Michelstadt',
        'Aschaffenburg', 'Schweinfurt', 'Coburg', 'Hof', 'Weiden', 'Amberg', 'Straubing',
        'Deggendorf', 'Landshut', 'Rosenheim', 'Traunstein', 'Berchtesgaden', 'Bad Reichenhall',
        'Freising', 'Erding', 'Dachau', 'Fürstenfeldbruck', 'Starnberg', 'Wolfratshausen',
        'Garmisch-Partenkirchen', 'Kempten', 'Kaufbeuren', 'Memmingen', 'Lindau', 'Friedrichshafen',
        'Ravensburg', 'Wangen im Allgäu', 'Biberach', 'Ehingen', 'Sigmaringen', 'Tuttlingen',
        'Rottweil', 'Villingen-Schwenningen', 'Donaueschingen', 'Singen', 'Radolfzell', 'Überlingen',
        'Tübingen', 'Reutlingen', 'Esslingen', 'Göppingen', 'Schwäbisch Gmünd', 'Aalen', 'Heidenheim',
        'Ellwangen', 'Schwäbisch Hall', 'Crailsheim', 'Ansbach', 'Schwabach', 'Erlangen',
        'Kiel', 'Lübeck', 'Flensburg', 'Neumünster', 'Norderstedt', 'Rendsburg', 'Itzehoe',
        'Husum', 'Heide', 'Elmshorn', 'Wedel', 'Pinneberg', 'Ahrensburg', 'Bad Oldesloe',
        'Lüneburg', 'Celle', 'Wolfenbüttel', 'Salzgitter', 'Goslar', 'Clausthal-Zellerfeld',
        'Hameln', 'Holzminden', 'Einbeck', 'Northeim', 'Osterode', 'Herzberg', 'Duderstadt',
    ],
    UA: [
        'Kyjev', 'Ľvov', 'Charkiv', 'Odesa', 'Dnipro', 'Záporožžie', 'Mukačevo', 'Užhorod',
        'Ternopil', 'Ivano-Frankivsk', 'Rivne', 'Lutsk', 'Chernivtsi', 'Chmelnyckij', 'Vinnycja',
        'Zhytomyr', 'Poltava', 'Čerkasy', 'Sumy', 'Mykolajiv', 'Cherson', 'Kryvyi Rih',
        'Mariupol', 'Luhansk', 'Donetsk', 'Simferopol', 'Sevastopol', 'Kerč', 'Jalta',
        'Berdyansk', 'Melitopol', 'Novoukrajinka', 'Kropyvnytskyi', 'Oleksandria',
        'Kremenchuk', 'Poltava', 'Myrhorod', 'Lubny', 'Konotop', 'Shostka', 'Romny',
        'Uman', 'Khmilnyk', 'Bar', 'Mohyliv-Podilskyi', 'Khmelnytskyi', 'Shepetivka',
        'Rivne', 'Kostopil', 'Sarny', 'Lutsk', 'Kovel', 'Volodymyr', 'Novovolynsk',
        'Drohobych', 'Boryslaw', 'Truskavets', 'Stryi', 'Boryslav', 'Kolomyja', 'Kolomia',
        'Kolomyia', 'Halych', 'Nadvirna', 'Tysmenytsia', 'Buchach', 'Chortkiv', 'Zbarazh',
        'Rohatyn', 'Zolochiv', 'Brody', 'Sokal', 'Yavoriv', 'Zhydachiv', 'Kamianka-Buzka',
        'Chernivtsi', 'Khotyn', 'Storozhynets', 'Vashkivtsi', 'Kitsman',
    ],
}

export const AMORTIZATION_RATE = 0.313

export const TAX_RATES = [0, 5, 10, 19, 20, 23]

export const DEFAULT_ENTRY: StravneRatesEntry = {
    validFrom: '2025-01-01',
    sk_5: 9.30,
    sk_12: 13.80,
    sk_18: 20.60,
    meals: { ranajky: 0.25, obed: 0.40, vecera: 0.35 },
    amortizationRate: 0.313,
    foreign: Object.fromEntries(
        COUNTRY_OPTIONS.filter(c => c.code !== 'SK').map(c => [
            c.code,
            { rate_12: 0, currency: c.currency },
        ])
    ),
}

export const DEFAULT_STRAVNE_RATES: StravneRates = [DEFAULT_ENTRY]
